### ISSUE TITLE
Combine with react-css-modules

### ISSUE THREAD

**Issue by grsmvg** [pluralsight/react-styleable#9]
Do you think there is an easy way to combine this with react-css-modules?

Btw; this package is awesome. Hope that more big react component projects will adopt this pattern.

**Comment by jaketrent** [comment]
Hey @grsmvg , I'm glad you're enjoying the packaging and finding use for it.  Yes, I also wish more component projects were CSS module-friendly in this way.  

react-css-modules solves similar problems in a different way.  I'm not sure how well they'd combine.  The string that is getting passed into styleName has more done to it than in react-styleable.  But I haven't looked into it much.  I'm interested in what you might find.

**Comment by grsmvg** [comment]
React-css-modules is mostly nice for simplifying syntax. The syntax would get verbose really quickly if you want to do some conditional classnames based on this.props.css. 

Let's say you want to add an optional `active` class to `button`, using the packages `classnames` and `react-styleable`:

```
<button className={classnames(this.props.css.button, { [this.props.css.active]: this.props.active })}></button>
```

I will write a simple HOC to glue `react-styleable` and `react-css-modules` together. Then the syntax will look like this again:

```
<button styleName={classnames('button', { active: this.props.active })}></button>
```

I will post an update here.

**Comment by jaketrent** [comment]
No current plan for going forward with this.  Closing for now.  If we get some new traction here, we can reopen.
